from typing import Optional, List
from fastapi import FastAPI, Query
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import httpx
import time
import os
import uvicorn
from . import search_club_website

app = FastAPI()
CONVEX_URL = os.environ["CONVEX_URL"]  # e.g. https://friendly-finch-619.convex.cloud


class Dive(BaseModel):
    user_id: str
    dive_number: int  # for upsert
    dive_date: int
    location: str
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    site: Optional[str] = None
    duration: float
    max_depth: float
    temperature: Optional[float] = None
    water_type: str
    visibility: Optional[float] = None
    weather: Optional[str] = None
    suit_thickness: Optional[float] = None
    lead_weights: Optional[float] = None
    club_name: Optional[str] = None
    club_website: Optional[str] = None
    instructor_name: Optional[str] = None
    notes: Optional[str] = None
    photo_storage_id: Optional[str] = None
    buddy_ids: List[str] = []
    equipment: List[str] = []
    # Note: logged_at and updated_at are server-generated by Convex


@app.post("/dives/upsert")
async def upsert_dive(dive: Dive):
    payload = dive.model_dump()
    # logged_at and updated_at are managed server-side by Convex

    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"{CONVEX_URL}/api/mutation",
            json={
                "path": "dives:upsertDive",
                "args": payload,
                "format": "json",
            },
        )
        resp.raise_for_status()
        result = resp.json()

        # Handle Convex error responses
        if "error" in result:
            return JSONResponse(
                status_code=400,
                content={"error": result["error"], "convex_error": True}
            )

        return result.get("value", result)


@app.get("/dives/{dive_id}")
async def get_dive_by_id(dive_id: str):
    """Get a single dive by its Convex document ID"""
    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"{CONVEX_URL}/api/query",
            json={
                "path": "dives:getDiveById",
                "args": {"id": dive_id},
                "format": "json",
            },
        )
        resp.raise_for_status()
        response_data = resp.json()

        # Handle Convex error responses
        if "error" in response_data:
            return JSONResponse(
                status_code=400,
                content={"error": response_data["error"], "convex_error": True}
            )

        result = response_data.get("value")

        if result is None:
            return JSONResponse(
                status_code=404,
                content={"error": f"Dive with id '{dive_id}' not found"}
            )

        return result


@app.get("/search-club")
def search_club(q: str = Query(..., description="Club name")):
    result = search_club_website(q)
    if result["success"]:
        return result
    return JSONResponse(status_code=404 if "No results" in result["error"] else 500, content=result)


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
